version: "3.8"

services:
  db:
    image: postgres:14
    env_file: .env
    restart: always
    expose:
      - '5432'
    ports:
      - '5432:5432'
    volumes:
      - group-project:/var/lib/postgresql/data
      - ./src/init_data:/docker-entrypoint-initdb.d

  web:
    image: node:lts
    working_dir: /repository/src
    env_file: .env
    environment:
      NODE_ENV: production
    depends_on:
      - db
    ports:
      - '3000:3000'
    volumes:
      - ./src:/repository/src
      - ./uploads:/repository/src/uploads
    command: sh -c "npm install && npm run testandrun"

volumes:
  group-project:
